services:
  antizapret-vpn:
    image: xtrime/antizapret-vpn:latest
    container_name: antizapret-vpn
    hostname: antizapret
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    build: .
    environment:
      - DOMAIN
      - PORT
      - CBC_CIPHERS
      - SCRAMBLE
      - DNS
      - DNS_RU
      - ADGUARD
      - TLS_CRYPT
    ports:
      - 1194:1194/tcp
      - 1194:1194/udp
    # dns:
    #   - 1.1.1.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/antizapret/result:/root/antizapret/result
      - /tmp/antizapret/temp:/root/antizapret/temp
      - ./keys:/etc/openvpn
      - ./config:/root/antizapret/config/custom
    sysctls:
      net.ipv4.conf.default.route_localnet: 1
      net.ipv4.ip_forward: 1
      net.ipv4.tcp_congestion_control: bbr
      net.ipv4.tcp_fastopen: 3
      net.ipv4.tcp_fin_timeout: 10
      net.ipv4.tcp_keepalive_intvl: 120
      net.ipv4.tcp_keepalive_probes: 3
      net.ipv4.tcp_keepalive_time: 600
      net.ipv4.tcp_retries2: 5
      net.ipv4.tcp_rmem: 4096 262143 4194304
      net.ipv4.tcp_slow_start_after_idle: 0
      net.ipv4.tcp_wmem: 4096 262143 4194304
      net.netfilter.nf_conntrack_generic_timeout: 600
      net.netfilter.nf_conntrack_icmp_timeout: 30
      net.netfilter.nf_conntrack_tcp_timeout_close: 10
      net.netfilter.nf_conntrack_tcp_timeout_close_wait: 60
      net.netfilter.nf_conntrack_tcp_timeout_established: 1800
      net.netfilter.nf_conntrack_tcp_timeout_fin_wait: 120
      net.netfilter.nf_conntrack_tcp_timeout_last_ack: 30
      net.netfilter.nf_conntrack_tcp_timeout_max_retrans: 300
      net.netfilter.nf_conntrack_tcp_timeout_syn_recv: 60
      net.netfilter.nf_conntrack_tcp_timeout_syn_sent: 120
      net.netfilter.nf_conntrack_tcp_timeout_time_wait: 120
      net.netfilter.nf_conntrack_tcp_timeout_unacknowledged: 300
      net.netfilter.nf_conntrack_udp_timeout: 120
      net.netfilter.nf_conntrack_udp_timeout_stream: 180
    logging:
      driver: json-file
      options:
        max-size: 100k
        max-file: 2
