name: Build
run-name: ${{ inputs.version }}

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: Version
        default: 0.0.0

concurrency:
  group: antizapret

env:
  DOCKER_BUILD_CHECKS_ANNOTATIONS: false
  DOCKER_BUILD_SUMMARY: false
  DOCKER_BUILD_RECORD_UPLOAD: false
  USERNAME: ${{ vars.USERNAME || 'xtrime' }}
  REPOSITORY: ${{ vars.REPOSITORY || 'xtrime/antizapret-vpn' }}
  VERSION: ${{ inputs.version }}

jobs:
  build:
    name: Build [${{ matrix.arch }}]
    runs-on: ${{ contains(matrix.arch, 'arm') && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set Metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ${{ env.REPOSITORY }}

      - name: Build Image
        uses: docker/build-push-action@v6
        id: build
        with:
          cache-from: type=gha,scope=build-${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=build-${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}
          labels: ${{ steps.metadata.outputs.labels }}
          outputs: type=image,"name=${{ env.REPOSITORY }}",push-by-digest=true,name-canonical=true,push=${{ github.event_name == 'workflow_dispatch' }}

      - name: Export Digests
        if: github.event_name == 'workflow_dispatch'
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload Digests
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: digests-linux-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  publish:
    name: Publish
    runs-on: ubuntu-24.04
    needs: build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set Metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REPOSITORY }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.VERSION }}

      - name: Download Digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Create Manifest & Push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REPOSITORY }}@sha256:%s ' *)

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          generate_release_notes: true
